# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295fc156cd1e4eefe530006a2555b4fe4c244bb46bedb2025bffb6615319c05ceed0f7582cfb2fa2d61294e4c8f5e6ce973ec4005dba2f04638aac2e5a2e97f9

test:
  secret_key_base: d2db5fc2458354d9a154f0bac2e0ab2ca9bc55d657aad71466f1f152b06f7d72fb6efea07c205090d897ca22322574982bf7f1d2930bc5790004a98763534102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
